name: Build & Release Windows App

on:
  push:
    tags:
      - "v*"
  pull_request:
    types: [closed]
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') || github.event.pull_request.merged == true
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Enable Windows build
        run: flutter config --enable-windows-desktop

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: game_member_generator_windows
          path: build/windows/x64/runner/Release
          overwrite: true

      - name: Prepare release folder
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir release
          xcopy build\windows\x64\runner\Release\* release\ /E /I

      - name: Zip build
        if: startsWith(github.ref, 'refs/tags/')
        run: Compress-Archive -Path release\* -DestinationPath game_member_generator_windows.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: game_member_generator_windows.zip
